LOGGER_NAME = "gaia"
LOGGER_SERVICE_NAME = "gaia-api"

ENVIRONMENT_LOCAL = "local"
ENVIRONEMENT_STG = "staging"
ENVIRONTMENT_PRD = "prod"

ALLOWED_ORIGINS = []
ALLOWED_STG_ORIGINS = []

SEVERITY_DEBUG = "debug"
SEVERITY_INFO = "info"
SEVERITY_WARNING = "warning"
SEVERITY_ERROR = "error"
SEVERITY_CRITICAL = "critical"

ERR_OUT_OF_SYNC = "health check is out of sync"